package bot.backend.nodes.events;

import bot.backend.nodes.events.utils.ClassField;
import bot.backend.nodes.categories.Category;
import bot.backend.nodes.events.utils.RequiredField;
import bot.backend.nodes.location.Location;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class ActiveEvent extends OutDoorEvent {

    @RequiredField
    public ActivityType activityType;

    public ActiveEvent(Location location, Category category, Time time) {
        super(location, category, time);
    }

    // TODO wait returning
    public enum ActivityType {
        SPORT, ROPE_PARK, YOGA, SNOWBOARD, RAFTING, DANCING
    }

	// generated by script at 22/06/2022 22:35:59
	public static final ClassField<ActiveEvent, ActivityType> ACTIVITY_TYPE = new ClassField<>(ActiveEvent::getActivityType, ActiveEvent::setActivityType, "activityType");
}
