package bot.backend.nodes.events;

import bot.backend.nodes.events.utils.ClassField;
import bot.backend.nodes.categories.Category;
import bot.backend.nodes.events.utils.RequiredField;
import bot.backend.nodes.location.Location;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

@Getter
@Setter
public class CrowdEvent extends ActiveEvent {

    @RequiredField
    public CrowdEventType type;

    public CrowdEvent(Location location, Category category, Time time) {
        super(location, category, time);
    }

    @AllArgsConstructor
    public enum CrowdEventType {
        FOOTBALL("Футбол"),
        BASKETBALL("Баскетбол"),
        Hockey("Хоккей"),
        TENNIS("Теннис"),
        FESTIVAL("Фестиваль"),
        FAIR("Ярмарка"),
        UNKNOWN("Что-то необычное");

        public static Map<String, CrowdEventType> map = new HashMap<>();

        static {
            Arrays.stream(values()).forEach(it -> map.put(it.realName, it));
        }

        private final String realName;
    }


	// generated by script at 23/06/2022 18:20:08
	public static final ClassField<CrowdEvent, CrowdEventType> TYPE = new ClassField<>(CrowdEvent::getType, CrowdEvent::setType, "type");
}
