package bot.backend.nodes.events;

import bot.backend.nodes.events.utils.ClassField;
import bot.backend.nodes.categories.Category;
import bot.backend.nodes.events.utils.RequiredField;
import bot.backend.nodes.location.Location;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.util.*;

@Getter
@Setter
public class CultureEvent extends OutDoorEvent {

    @RequiredField
    public Set<CultureType> cultureTypes;

    public CultureEvent(Location location, Category category, Time time) {
        super(location, category, time);
    }

    public CultureEvent(Location location, Category category, Time time, Set<CultureType> cultureTypes) {
        super(location, category, time);
        this.cultureTypes = cultureTypes;
    }

    @AllArgsConstructor
    public enum CultureType {
        MOVIE("В кино"),
        THEATRE("В театр"),
        OPERA("Опера"),
        BALLET("Балет"),
        GALLERY("Выставка/галерея"),
        MUSICAL("На мюзикл");

        public static Map<String, CultureType> map = new HashMap<>();

        static {
            Arrays.stream(values()).forEach(it -> map.put(it.realName, it));
        }

        private final String realName;
    }



	// generated by script at 22/06/2022 22:35:59
	public static final ClassField<CultureEvent, Set<CultureType>> TYPE = new ClassField<>(CultureEvent::getCultureTypes, CultureEvent::setCultureTypes, "type");
}
