package bot.backend.nodes.events;

import bot.backend.nodes.events.utils.ClassField;
import bot.backend.nodes.categories.Category;
import bot.backend.nodes.location.Location;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class OutDoorEvent extends Event {

    public OutDoorEvent(Location location, Category category, Time time) {
        super(location, category, time);
    }


	// generated by script at 23/06/2022 18:20:08
}
