//package bot.backend.nodes.events;
//
import bot.backend.nodes.events.utils.ClassField;
//import bot.backend.nodes.events.utils.ClassField;
//import bot.backend.nodes.categories.Category;
//import bot.backend.nodes.events.utils.RequiredField;
//import bot.backend.nodes.location.Location;
//import bot.backend.nodes.restriction.utils.TypedEnum;
//import lombok.AllArgsConstructor;
//import lombok.Getter;
//import lombok.Setter;
//
//import java.util.Arrays;
//import java.util.HashMap;
//import java.util.Map;
//
//@Getter
//@Setter
//public class SportEvent extends ActiveEvent {
//
//    @RequiredField
//    public SportType sportType;
//
//    public SportEvent(Location location, Category category, Time time) {
//        super(location, category, time);
//    }
//
//    public SportEvent(Location location, Category category, Time time, SportType sportType) {
//        super(location, category, time);
//        this.sportType = sportType;
//    }
//
//
//
//
//
//	// generated by script at 22/06/2022 22:35:59
//	public static final ClassField<SportEvent, SportType> SPORT_TYPE = new ClassField<>(SportEvent::getSportType, SportEvent::setSportType, "sportType");

	// generated by script at 23/06/2022 18:20:08
//}
