name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Execute Gradle test
        run: ./gradlew test

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v3

  build_docker_image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: read-docker-image-identifiers
        name: Read Docker Image Identifiers
        run: echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Build Spring Boot Docker image (sha)
        run: ./gradlew bootBuildImage --imageName=ghcr.io/${{ env.IMAGE_REPOSITORY }}:${{ github.sha }}

      - name: Build Spring Boot Docker image (latest)
        run: ./gradlew bootBuildImage --imageName=ghcr.io/${{ env.IMAGE_REPOSITORY }}:latest

      - name: Push Docker image (sha)
        run: docker push ghcr.io/${{ env.IMAGE_REPOSITORY }}:${{ github.sha }}

      - name: Push Docker image (latest)
        run: docker push ghcr.io/${{ env.IMAGE_REPOSITORY }}:latest
